package com.hiennt.pizza.utils;

public enum Errors {
	CUS_ERROR("001", "CUSTOMER ERROR"),
	CUS_ERROR_EXITS("002","YOU ARE ENTERING A MISSING FIELD OF CUSTOMER"),
	CUS_ERROR_NAME("003","NAME EXISTS"),
	CUS_ERROR_ZIP("004","ZIP EXISTS"),
	CUS_ERROR_PHONE("005","PHONE EXISTS"),
	CUS_ERROR_ID("006","CANNOT FIND CUSTOMER FROM THIS ID"),
	PRO_ERROR("011","PRODUCT ERROR"),
	PRO_ERROR_EXISTS("012","YOU ARE ENTERING A MISSING FIELD OF PRODUCT"),
	PRO_ERROR_ID("013","ID NOT EXISTS"),
	PRO_ERROR_NAME("014","NAME EXIST"),
	INV_ERROR("021","INVOICE ERROR"),
	INV_ERROR_EXISTS("022","YOU ARE ENTERING A MISSING FIELD OF CUSTOMER"),
	INV_ERROR_ID("023","ID EXISTS"),
	INV_ERROR_CUSANDPRO("024","CUSTOMER ID OR PRODUCT ID NOT EXISTS");
//	INV_ERROR_ID("022","ID NOT EXISTS"),
//	INV_ERROR_NUMBERS("023","NUMBER NOT EXIST"),
//	INV_ERROR_ISSUEDATE("024","ISSUEDATE NOT EXISTS"),
//	INV_ERROR_TOTALPAYMENT("025","TOTALPAYMENT NOT EXISTS"),
//	INV_ERROR_ID_CUS("026","CUSID NOT EXISTS IN INVOICE ID"),
//	INV_ERROR_ID_PRO("027","PROiD NOT EXISTS IN INVOICE ID");
	
	
	private final String id;
	private final String message;
	
	Errors(String id, String message) {
		this.id = id;
		this.message = message;
	}
	
	public String getId() {return id;}
	
	public String getMessage() {return message;}
}
